### ISSUE TITLE
langchain 调用千帆 异常 

### ISSUE THREAD

**Issue by dessun888** [baidubce/bce-qianfan-sdk#311]
### System Info

qianfan                  0.3.3
Ubuntu 20.04
langchain                0.1.10
langchain-cli            0.0.21
langchain-community      0.0.25
langchain-core           0.1.28
langchain-text-splitters 0.0.1

### Reproduction

[INFO] [03-05 14:00:05] oauth.py:207 [t:139649604084096]: trying to refresh access_token for ak `AUROeZ***`
[INFO] [03-05 14:00:06] oauth.py:220 [t:139649604084096]: sucessfully refresh access_token
Additional kwargs key sentence_id already exists in left dict and value has unsupported type <class 'int'>.
[None]

源代码 
from langchain_community.chat_models import QianfanChatEndpoint

    openai = ChatOpenAI(model_name="gpt-3.5-turbo")
    #ollama = Ollama(model="gemma",base_url="")
    gemma = Ollama(model="gemma:7b")
    qwen = Ollama(model="qwen:7b")

    tongyi = Tongyi()
    qianfan =  QianfanChatEndpoint(
        streaming=True,
    )

    #models  = [openai,gemma,tongyi] 

    models  = [qianfan]

    contents = []
    for model in models : 
        try :
            agent_executor = get_agent(model)
            content = agent_executor.invoke(
                {
                    "input": "Take 3 to the fifth power ,Without explanation or further clarification ",
                    "chat_history":""
                }
            )
        except Exception as e :
            print(str(e))
            content= None 
        contents.append(content)

    print(contents)

**Comment by dessun888** [comment]
堆栈跟踪
Additional kwargs key created already exists in left dict and value has unsupported type <class 'int'>.
Traceback (most recent call last):
  File "/data/apps/lanchain-server/utils/math_tools.py", line 82, in <module>
    content = agent_executor.invoke(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py", line 1391, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py", line 1097, in _take_next_step
    [
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py", line 1097, in <listcomp>
    [
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py", line 1125, in _iter_next_step
    output = self.agent.plan(
             ^^^^^^^^^^^^^^^^
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py", line 486, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2446, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2433, in transform
    yield from self._transform_stream_with_config(
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1513, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2397, in _transform
    for output in final_pipeline:
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1051, in transform
    for chunk in input:
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 4173, in transform
    yield from self.bound.transform(
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1061, in transform
    yield from self.stream(final, config, **kwargs)
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 250, in stream
    raise e
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 241, in stream
    generation += chunk
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/outputs/chat_generation.py", line 57, in __add__
    generation_info = merge_dicts(
                      ^^^^^^^^^^^^
  File "/data/apps/conda/envs/langchain/lib/python3.11/site-packages/langchain_core/utils/_merge.py", line 38, in merge_dicts
    raise TypeError(
TypeError: Additional kwargs key created already exists in left dict and value has unsupported type <class 'int'>.

**Comment by Dobiichi-Origami** [comment]
这个是由于 `langchain-core` 的更新导致的字段不兼容问题，目前已有多个用户通过多个渠道反馈了这一问题。
如果没有对高版本的强制依赖，现阶段的解决方案，我们推荐按照该 [PR](https://github.com/langchain-ai/langchain/issues/16352#issuecomment-1905770008) 的建议将 `langchain-core` 降级至 `0.1.12`

我们未来计划对 Langchain 的千帆封装做对 OpenAI 格式的对齐以解决种种不兼容问题，且就这一问题，现在也有新的 [PR](https://github.com/langchain-ai/langchain/pull/18445) 提交给了 Langchain 社区。

**Comment by Dobiichi-Origami** [comment]
已在 langchain 最新版本的分支中合入修复代码
