### ISSUE TITLE
 fetch is not defined  node@16.20.2  @baiducloud/qianfan@0.0.6

### ISSUE THREAD

**Issue by lqomg** [baidubce/bce-qianfan-sdk#370]
### System Info

```
Unhandled Rejection at: Promise {
  <rejected> Error: Failed to get access token: fetch is not defined
      at ChatCompletion._callee$ (F:\work\xora\node_modules\@baiducloud\qianfan\dist\bundle.js:8066:23)
      at tryCatch (F:\work\xora\node_modules\@baiducloud\qianfan\dist\bundle.js:248:18)
      at Generator.<anonymous> (F:\work\xora\node_modules\@baiducloud\qianfan\dist\bundle.js:336:19)
      at Generator.throw (F:\work\xora\node_modules\@baiducloud\qianfan\dist\bundle.js:277:23)
      at asyncGeneratorStep (F:\work\xora\node_modules\@baiducloud\qianfan\dist\bundle.js:537:26)
      at _throw (F:\work\xora\node_modules\@baiducloud\qianfan\dist\bundle.js:559:11)
```

### Reproduction

```js
const { ChatCompletion } = require("@baiducloud/qianfan");
const { createUuid, logger } = require("../utils");
const client = new ChatCompletion();
const prompt = async (msg) => {
  const content = msg
  const resp = await client.chat({
    messages: [
      {
        role: "user",
        content,
      },
    ],
  });
  console.log(resp);
  logger.info(resp);
};

module.exports = prompt;

```

**Comment by wangting829** [comment]
您好，麻烦问下在哪个环境下使用的，node or 浏览器

**Comment by lqomg** [comment]
> 您好，麻烦问下在哪个环境下使用的，node or 浏览器

node环境 @wangting829

**Comment by itagan** [comment]
![Uploading 截屏2024-03-23 00.49.57.png…]()

**Comment by itagan** [comment]
可能是因为：Node.js 从 v17.5.0 版本开始原生支持 Fetch API

**Comment by wangting829** [comment]
你好，建议升级node版本哈，后期会支持低版本的node～
