### ISSUE TITLE
限流依赖库升级

### ISSUE THREAD

**Issue by wangting829** [baidubce/bce-qianfan-sdk#382]
### System Info

@baiducloud/qianfan: 0.0.7

### Reproduction

/Users/wangting31/Documents/openai-node/openai-node/node_modules/@baiducloud/qianfan/dist/bundle.js:4652
      this.mutex = new Mutex();
                   ^

TypeError: Mutex is not a constructor
    at new RateLimiter (/Users/wangting31/Documents/openai-node/openai-node/node_modules/@baiducloud/qianfan/dist/bundle.js:4652:20)
    at new Fetch (/Users/wangting31/Documents/openai-node/openai-node/node_modules/@baiducloud/qianfan/dist/bundle.js:4815:26)
    at new BaseClient (/Users/wangting31/Documents/openai-node/openai-node/node_modules/@baiducloud/qianfan/dist/bundle.js:6635:28)
    at _callSuper (/Users/wangting31/Documents/openai-node/openai-node/node_modules/@baiducloud/qianfan/dist/bundle.js:141:104)
    at new ChatCompletion (/Users/wangting31/Documents/openai-node/openai-node/node_modules/@baiducloud/qianfan/dist/bundle.js:7172:14)
    at Object.<anonymous> (/Users/wangting31/Documents/openai-node/openai-node/src/chatCompletion.js:23:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)

**Comment by wangting829** [comment]
0.0.7版本修复
