### ISSUE TITLE
使用千帆 sdk 报超时，Auth request failed: Timeout deadline: 180000 MILLISECONDS, actual: 180000 MILLISECONDS

### ISSUE THREAD

**Issue by astro842** [baidubce/bce-qianfan-sdk#552]
### System Info

     <dependency>
            <groupId>com.baidubce</groupId>
            <artifactId>qianfan</artifactId>
            <version>0.0.1</version>
        </dependency>

### Reproduction

 com.baidubce.qianfan.model.exception.RequestException: Auth request failed: Timeout deadline: 180000 MILLISECONDS, actual: 180000 MILLISECONDS

使用该 sdk，sdk 自行维护Auth token，多请求几次就会报超时

**Comment by Azure99** [comment]
请更新到0.0.5版本，旧版5秒就会失效，新版本是3600秒。
另外可以通过QIANFAN_ACCESS_TOKEN_REFRESH_MIN_INTERVAL来设置失效时间，最长是30天，建议可以增大到一天。

**Comment by hxyfj** [comment]
> 请更新到0.0.5版本，旧版5秒就会失效，新版本是3600秒。 另外可以通过QIANFAN_ACCESS_TOKEN_REFRESH_MIN_INTERVAL来设置失效时间，最长是30天，建议可以增大到一天。

请问sdk要接口 可以直接修改QIANFAN_ACCESS_TOKEN_REFRESH_MIN_INTERVAL 吗，看sdk里面这个值是私有的，是只能自己改sdk吗

**Comment by hxyfj** [comment]
> 请更新到0.0.5版本，旧版5秒就会失效，新版本是3600秒。 另外可以通过QIANFAN_ACCESS_TOKEN_REFRESH_MIN_INTERVAL来设置失效时间，最长是30天，建议可以增大到一天。

请问sdk有接口 可以直接修改QIANFAN_ACCESS_TOKEN_REFRESH_MIN_INTERVAL 吗，看sdk里面这个值是私有的，是只能自己改sdk吗

**Comment by astro842** [comment]
> 请更新到0.0.5版本，旧版5秒就会失效，新版本是3600秒。 另外可以通过QIANFAN_ACCESS_TOKEN_REFRESH_MIN_INTERVAL来设置失效时间，最长是30天，建议可以增大到一天。

Caused by: org.apache.hc.core5.http.ConnectionRequestTimeoutException: Timeout deadline: 180000 MILLISECONDS, actual: 180000 MILLISECONDS
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.acquireEndpoint(InternalExecRuntime.java:120) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:125) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:113) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162) ~[httpclient5-5.3.1.jar!/:5.3.1]
	at com.baidubce.qianfan.util.http.HttpClient.execute(HttpClient.java:81) ~[qianfan-0.0.5.jar!/:?]
	at com.baidubce.qianfan.util.http.HttpClient.executeJson(HttpClient.java:59) ~[qianfan-0.0.5.jar!/:?]
	at com.baidubce.qianfan.util.http.HttpRequest.executeJson(HttpRequest.java:116) ~[qianfan-0.0.5.jar!/:?]
	at com.baidubce.qianfan.core.auth.QianfanOAuth.sign(QianfanOAuth.java:84) ~[qianfan-0.0.5.jar!/:?]



已升级到0.0.5版本，服务跑几天还是会出现超时，请问是什么原因呢

**Comment by Azure99** [comment]
@astro842 在流式调用的场景下，如果没有迭代完全部数据，则不会触发Response的close，进而导致连接没有被释放。
在0.0.9版本中优化了此行为，使用forEachRemaining迭代数据时，能够保证连接释放；通过hasNext/next迭代数据时，如果希望提前终止迭代，或触发了异常，则需要显式调用close方法，或者通过try with resource语法糖。

可以升级到0.0.9版本后，按上述方法排查代码有无问题。
