### ISSUE TITLE
openai adapter接口不支持ernie-speed-8k，提示 finish_reason key_error

### ISSUE THREAD

**Issue by kbaicai** [baidubce/bce-qianfan-sdk#595]
### System Info

qianfan version:0.3.15

### Reproduction

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await response(scope, receive, send)
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/responses.py", line 257, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
    raise exceptions[0]
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/root/anaconda3/lib/python3.11/site-packages/starlette/responses.py", line 249, in stream_response
    async for chunk in self.body_iterator:
  File "/root/anaconda3/lib/python3.11/site-packages/qianfan/common/client/openai_adapter.py", line 86, in stream
    async for data in resp:
  File "/root/anaconda3/lib/python3.11/site-packages/qianfan/extensions/openai/adapter.py", line 459, in _chat_stream
    None if not res["is_end"] else res["finish_reason"]
                                   ~~~^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/qianfan/resources/typing.py", line 180, in __getitem__
    raise KeyError(item)
KeyError: 'finish_reason'

**Comment by kbaicai** [comment]
/root/anaconda3/lib/python3.11/site-packages/qianfan/extensions/openai/adapter.py 里把 res['finish_reason'] 改成 res.get("finish_reason", "normal") 就可以了

**Comment by danielhjz** [comment]
`qianfan==0.3.17` 已修复

> /root/anaconda3/lib/python3.11/site-packages/qianfan/extensions/openai/adapter.py 里把 res['finish_reason'] 改成 res.get("finish_reason", "normal") 就可以了
